version: '3.8'
services:
  php:
    image: php:8.1.22-apache
    volumes:
      - ./app/src:/var/www/html
    ports:
      - "8080:80"
  
  node:
    image: node:20.11.1-slim
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - php
