version: '3.8'
services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
  node:
    image: node:20.11.1-slim
    volumes:
      - ./src:/app
      - /src/node_modules
    working_dir: /app
    command: sh -c "npm install && npx tsc -w"
    depends_on:
      - php
